name: aurpublish

on:
  # Allow manual start
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: aur
    container:
      image: ghcr.io/greyltc/archlinux:latest
      options: -u root -v ${{ github.workspace }}:/workdir:rw
    steps:
    - name: Install dependencies
      run: pacman -Syu --overwrite="*" --needed --noconfirm --noprogressbar git openssh

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Configure ssh
      run: |
        mkdir -p ~/.ssh
        cat > ~/.ssh/config <<EOF
        Host aur
          Port 22
          User aur
          IdentityFile ~/.ssh/key
          HostName aur.archlinux.org
        EOF

        echo "$KEY" > ~/.ssh/key
        chmod -R 700 ~/.ssh
        ssh-keyscan aur.archlinux.org >> ~/.ssh/known_hosts
      env:
        KEY: ${{ secrets.SSH_KEY }}
    - name: Setup aurpublish
      run: ./.helpers/aur/pub setup
    - name: Publish pkgbuilds
      if: ${{ !env.ACT }}
      run: |
        git reset --hard
        git config user.email "ahmubashshir@gmail.com"
        git config user.name "Mubashshir"

        for each in */;do
          [[ -f "$each/.noaur" ]] && continue
          [[ -f "$each/PKGBUILD" ]] || continue
          (
            source "$each/PKGBUILD"
            printf '::group::Publish %s\n' "${pkgbase:-$pkgname}"
          )
          ./.helpers/aur/pub -p "$each"
          ./.helpers/aur/pub    "$each"
          printf '::endgroup::\n'
        done

    - name: Push changes
      if: ${{ !env.ACT }}
      run: git push
